name: npm-publish
on:
  push:
    branches:
      - master
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Run linting
        run: npm run lint
      - name: Run tests
        run: npm test -- --ci
      - name: Extract version from package.json
        id: extract_version
        uses: Saionaro/extract-package-version@v1.0.6
      - name: Print version
        run: echo ${{ steps.extract_version.outputs.version }}
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ github.token }}
          prerelease: false
          title: v${{ steps.extract_version.outputs.version }}
          automatic_release_tag: v${{ steps.extract_version.outputs.version }}
      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}