name: Push to master
on:
  push:
    branches:
      - master
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts

      - name: Linting
        run: yarn lint
      
      - name: Build
        run: yarn build
      
      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
      
      - name: Extract version from package.json
        id: extract_version
        uses: Saionaro/extract-package-version@v1.2.1

      - name: Create release on github
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          prerelease: false
          title: v${{ steps.extract_version.outputs.version }}
          automatic_release_tag: v${{ steps.extract_version.outputs.version }}
