name: npm-publish
on:
  push:
    branches:
      - master
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.0.0
        with:
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Run linting
        run: npm run lint
      - name: Run tests
        run: npm test -- --ci
      - name: Check package version
        id: cpv
        uses: PostHog/check-package-version@v2
      - uses: marvinpinto/action-automatic-releases@latest
        if: ${{ steps.cpv.outputs.is-new-version == 'true' }}
        with:
          repo_token: ${{ github.token }}
          prerelease: false
          title: v${{ steps.extract_version.outputs.version }}
          automatic_release_tag: v${{ steps.cpv.outputs.committed-version }}
      - name: Publish package
        run: npm publish
        if: ${{steps.cpv.outputs.is-new-version == 'true' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}