name: pull-request
on:
  pull_request:

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Run linting
        run: npm run lint
      - name: Run tests
        run: npm test -- --ci
