name: temp-pull-request
on:
  pull_request:

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Extract version from package.json
        id: extract_version
        uses: Saionaro/extract-package-version@v1.1.1
        run: echo ${{ steps.extract_version.outputs.version }}
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Print latest published version
        run: echo ${{ steps.package-version.outputs.current-version }}
      - name: Should this be published
        run: echo ${{ steps.extract_version.outputs.version > steps.package-version.outputs.current-version }}
