name: temp-pull-request
on:
  pull_request:

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: paralenz/actions/setup-node@v1.1.3
        with:
            registry-url: http://registry.npmjs.org
      - name: test paralenz/make-release
        uses: paralenz/actions/make-release@1.1.3
      # - name: Check package version
      #   id: cpv
      #   uses: PostHog/check-package-version@v2
      # - name: Should this be published
      #   if: ${{steps.cpv.outputs.is-new-version == 'true' }}
      #   run: echo "Publish this!!!"
