name: temp-pull-request
on:
  pull_request:

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Check package version
        id: cpv
        uses: PostHog/check-package-version@v2
      - name: Should this be published
        if: ${{steps.cpv.outputs.is-new-version == 'true' }}
        run: echo "Publish this!!!"
