name: temp-pull-request
on:
  pull_request:

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      # - name: Extract version from package.json
      #   id: extract_version
      #   uses: Saionaro/extract-package-version@v1.1.1
      # - name: Print version version in package.json
      #   run: echo ${{ steps.extract_version.outputs.version }}
      - name: Check package version
        id: cpv
        uses: PostHog/check-package-version@v2
      # - name: Echo output
        # run: |
        #   echo "Committed version: ${{ steps.cpv.outputs.committed-version }}"
        #   echo "Published version: ${{ steps.cpv.outputs.published-version }}"
        #   echo "Is new version: ${{ steps.cpv.outputs.is-new-version }}"
      # - name: Print latest published version
      #   run: echo ${{ steps.package-version.outputs.current-version }}
      - name: Should this be published
        if: ${{steps.cpv.outputs.is-new-version}}
        run: echo "Publish this!!!"
